backend:
  name: git-gateway
  branch: main
  identity_url: "https://www.pablonouvelle.com/.netlify/identity"
  gateway_url: "https://www.pablonouvelle.com/.netlify/git/github"
  squash_merges: true

media_folder: "src/static/images/album"
public_folder: "/images/album"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - label: "Releases"
    name: "content"
    files:
      - label: "Releases"
        name: "releases"
        file: "src/content/albums.md"
        editor:
          preview: false
        fields:
          - label: Release
            label_singular: Release
            name: albums
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Cover, name: cover, widget: image, allow_multiple: false }
              - { label: Link, name: link, widget: string }
