name: Fetch Bandsintown Events

on:
    push:
    schedule:
        -   cron:  '0 5 * * *'

jobs:
    fetch:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Parse events.json file
                run: "curl 'https://rest.bandsintown.com/artists/pablo%20nouvelle/events?app_id=${{ secrets.BANDINTOWN_APP_ID }}' | jq '[.[] | {url, datetime, venue: {name: .venue.name, city: .venue.city}}]' -c > src/content/events.json"

            -   name: Extract branch name
                shell: bash
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
                id: extract_branch

            -   name: Commit changed files
                uses: stefanzweifel/git-auto-commit-action@v2.5.0
                with:
                    commit_message: Update Events
                    branch: ${{ steps.extract_branch.outputs.branch }}
                    file_pattern: src/content/events.json
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
