name: Fetch Bandsintown Events

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v1
            -   name: Download events
                uses: wei/wget@v1
                with:
                    args: -O src/content/events.json https://rest.bandsintown.com/artists/pablo%20nouvelle/events?app_id=${{ secrets.BANDINTOWN_APP_ID }}
            -   name: Commit changed files
                uses: stefanzweifel/git-auto-commit-action@v2.5.0
                with:
                    commit_message: Update Events
                    branch: ${{ github.head_ref }}
                    file_pattern: src/content/events.json
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
