name: Run Eslint

on:
  push:
    branches:
      - master
    paths:
      - '**.js'
      - '**.vue'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2

      -   uses: bahmutov/npm-install@v1

      -   run: npm run lint-fix

      -   uses: stefanzweifel/git-auto-commit-action@v4.1.6
          with:
            commit_message: "Chore: Lint JavaScript and Vue files"
