name: Run Eslint

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.vue'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - run: npm ci

      - run: npm run lint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: Lint JavaScript and Vue files"
          commit_author: GitHub Actions <actions@github.com>
